#include "user_interface.h"

void	ui_style_button(void)
{
	GuiSetStyle(DEFAULT, TEXT_SIZE, 50);
	GuiSetStyle(DEFAULT, TEXT_SPACING, 5);
	GuiSetStyle(DEFAULT, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);

	GuiSetStyle(BUTTON, TEXT_COLOR_NORMAL, ColorToInt(WHITE));
	GuiSetStyle(BUTTON, TEXT_COLOR_FOCUSED, ColorToInt(WHITE));
	GuiSetStyle(BUTTON, TEXT_COLOR_PRESSED, ColorToInt(RED));

	GuiSetStyle(BUTTON, BASE_COLOR_NORMAL, ColorToInt(GRAY));
	GuiSetStyle(BUTTON, BASE_COLOR_FOCUSED, ColorToInt(DARKGRAY));
	GuiSetStyle(BUTTON, BASE_COLOR_PRESSED, ColorToInt(DARKGRAY));

	GuiSetStyle(BUTTON, BORDER_COLOR_NORMAL, ColorToInt(DARKBLUE));
	GuiSetStyle(BUTTON, BORDER_COLOR_FOCUSED, ColorToInt(DARKBLUE));
	GuiSetStyle(BUTTON, BORDER_COLOR_PRESSED, ColorToInt(RED));
}

void	ui_style_textbox(void)
{
	GuiSetStyle(DEFAULT, TEXT_SIZE, 60);
	GuiSetStyle(DEFAULT, TEXT_SPACING, 10);
	GuiSetStyle(DEFAULT, TEXT_ALIGNMENT, TEXT_ALIGN_LEFT);

	GuiSetStyle(TEXTBOX, TEXT_COLOR_NORMAL, ColorToInt(BLACK));
	GuiSetStyle(TEXTBOX, TEXT_COLOR_FOCUSED, ColorToInt(BLACK));
	GuiSetStyle(TEXTBOX, TEXT_COLOR_PRESSED, ColorToInt(BLACK));

	GuiSetStyle(TEXTBOX, BASE_COLOR_NORMAL, ColorToInt(WHITE));
	GuiSetStyle(TEXTBOX, BASE_COLOR_FOCUSED, ColorToInt(WHITE));
	GuiSetStyle(TEXTBOX, BASE_COLOR_PRESSED, ColorToInt(WHITE));

	GuiSetStyle(TEXTBOX, BORDER_COLOR_NORMAL, ColorToInt(DARKBLUE));
	GuiSetStyle(TEXTBOX, BORDER_COLOR_FOCUSED, ColorToInt(DARKBLUE));
	GuiSetStyle(TEXTBOX, BORDER_COLOR_PRESSED, ColorToInt(DARKBLUE));
}

void	ui_style_panel(void)
{
	GuiSetStyle(DEFAULT, TEXT_SIZE, 20);
	GuiSetStyle(DEFAULT, TEXT_SPACING, 10);
	GuiSetStyle(DEFAULT, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);
}

void	ui_style_suggestion(void)
{
	GuiSetStyle(DEFAULT, TEXT_SIZE, 60);
	GuiSetStyle(DEFAULT, TEXT_SPACING, 10);
	GuiSetStyle(DEFAULT, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);
}
